### PR TITLE
using an absolute url in the model rather than a helper method

### LINKED ISSUE #991: Curry is not appearing to work with opscode-bookbooks/iis
Reported internally at Chef this morning:

"so curry doesn't appear to be working on opscode-cookbooks/iis -> https://github.com/opscode-cookbooks/iis/pull/144. I just clicked "evaluate repository" under https://supermarket.chef.io/curry/repositories and waiting a minute and did it again and despite the website making promises to me about success I'm not seeing it on the PR."

I took a look at the Sentry logs and this is the stack trace we're getting when this error is encountered.

NoMethodError: undefined method `chef_blog_url' for #<Curry::UnauthorizedCommitAuthorComment:0x000000057a5508>

Stacktrace (most recent call first):

  File "unauthorized_commit_author_comment.rb", line 47, in block in comment_body
    blog.](#{chef_blog_url('2014/06/23/changes-to-the-contributor-license-agreement-process')})
  File "unauthorized_commit_author_comment.rb", line 39, in tap
    [].tap do |parts|
  File "unauthorized_commit_author_comment.rb", line 39, in comment_body
    [].tap do |parts|
  File "unauthorized_commit_author_comment.rb", line 28, in call
    comment_body
  File "pull_request_annotator.rb", line 67, in each
    actions.each(&:call)
  File "pull_request_annotator.rb", line 67, in annotate
    actions.each(&:call)
  File "cla_validation_worker.rb", line 15, in perform
    Curry::PullRequestAnnotator.new(pull_request).annotate
  File "sidekiq/processor.rb", line 52, in block (2 levels) in process
    worker.perform(*cloned(msg['args']))
  File "sidekiq/middleware/chain.rb", line 122, in call
    final_action.call
  File "sidekiq/middleware/chain.rb", line 122, in block in invoke
    final_action.call
  File "new_relic/agent/instrumentation/sidekiq.rb", line 33, in block in call
    yield
  File "new_relic/agent/instrumentation/controller_instrumentation.rb", line 365, in perform_action_with_newrelic_trace
    yield
  File "new_relic/agent/instrumentation/sidekiq.rb", line 29, in call
    perform_action_with_newrelic_trace(trace_args) do
  File "sidekiq/middleware/chain.rb", line 124, in block in invoke
    chain.shift.call(*args, &traverse_chain)
  File "sidetiq/middleware/history.rb", line 8, in call
    yield
  File "sidekiq/middleware/chain.rb", line 124, in block in invoke
    chain.shift.call(*args, &traverse_chain)
  File "sidekiq/middleware/server/active_record.rb", line 6, in call
    yield
  File "sidekiq/middleware/chain.rb", line 124, in block in invoke
    chain.shift.call(*args, &traverse_chain)
  File "sidekiq/middleware/server/retry_jobs.rb", line 74, in call
    yield
  File "sidekiq/middleware/chain.rb", line 124, in block in invoke
    chain.shift.call(*args, &traverse_chain)
  File "sidekiq/middleware/server/logging.rb", line 11, in block in call
    yield
  File "sidekiq/logging.rb", line 22, in with_context
    yield
  File "sidekiq/middleware/server/logging.rb", line 7, in call
    Sidekiq::Logging.with_context("#{worker.class.to_s} JID-#{item['jid']}") do
  File "sidekiq/middleware/chain.rb", line 124, in block in invoke
    chain.shift.call(*args, &traverse_chain)
  File "sidekiq/middleware/chain.rb", line 127, in call
    traverse_chain.call
  File "sidekiq/middleware/chain.rb", line 127, in invoke
    traverse_chain.call
  File "sidekiq/processor.rb", line 51, in block in process
    Sidekiq.server_middleware.invoke(worker, msg, queue) do
  File "sidekiq/processor.rb", line 94, in stats
    yield
  File "sidekiq/processor.rb", line 50, in process
    stats(worker, msg, queue) do
  File "celluloid/calls.rb", line 25, in public_send
    obj.public_send(@method, *@arguments, &_block)
  File "celluloid/calls.rb", line 25, in dispatch
    obj.public_send(@method, *@arguments, &_block)
  File "celluloid/calls.rb", line 122, in dispatch
    super(obj)
  File "celluloid/actor.rb", line 322, in block in handle_message
    message.dispatch(@subject)
  File "celluloid/actor.rb", line 416, in block in task
    yield
  File "celluloid/tasks.rb", line 55, in block in initialize
    yield
  File "celluloid/tasks/task_fiber.rb", line 13, in block in create
    yield

### PR DESCRIPTION
**Pull request by nellshamrell**
Fixes #991

### CODE REVIEW

File: app/models/curry/unauthorized_commit_author_comment.rb [hunk 1]
```diff
@@ -44,7 +44,7 @@ def comment_body
         verified email address. To become authorized to contribute, you will
         need to sign the Contributor License Agreement (CLA) as an individual or
         on behalf of your company. [You can read more on Chef's
-        blog.](#{chef_blog_url('2014/06/23/changes-to-the-contributor-license-agreement-process')})
+        blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)
```
Comment (smith) [inline app/models/curry/unauthorized_commit_author_comment.rb]: Would it be better to `include CustomUrlHelper` in this class? I'm very :-1: on hard-coding URLs.

Comment (nellshamrell) [inline app/models/curry/unauthorized_commit_author_comment.rb]: It's possible...but I don't think including Helpers in models is a good practice either.  Perhaps we could create a constant and refer to it both from here in the model and from the method in the helper?

Comment (nellshamrell) [inline app/models/curry/unauthorized_commit_author_comment.rb]: I'd also be fine with including a method in a module in lib/, as suggested in this post http://codefol.io/posts/Where-Do-I-Put-My-Code

Comment (raskchanky) [inline app/models/curry/unauthorized_commit_author_comment.rb]: If both views and models need access to the methods inside `CustomUrlHelper`, I don't think it would hurt to just move the entire module into `lib`.

Comment (smith) [inline app/models/curry/unauthorized_commit_author_comment.rb]: Note that CustomUrlHelper is pretty much a placeholder for [Chef::Web::Core::URLHelpers](https://github.com/chef/chef-web-core/blob/master/lib/chef/web/core/url_helpers.rb), but that project is not yet open sourced.

I don't care what the solution is as long as it doesn't involve hard-coding URLs and making things needlessly complex. I have no problem with including a helper in a model (it's just a module with methods, and if we need those methods let's use them) but if it makes anyone feel better by doing it some other way then let's do that.

Comment (nellshamrell) [inline app/models/curry/unauthorized_commit_author_comment.rb]: Thought about this long and hard...I think the risk is a little too great to move the helper methods into lib for this breakfix.  For now, I will include CustomUrlHelper in the model (we're already doing this with the application controller), but will be creating a ticket to refactor the helper into lib in the future.

Just implemented this and pushed to this branch, this is now ready for review again.

**Comment by btm** [comment]
squash the commits? :+1:

**Comment by nathenharvey** [comment]
:+1:
