### PR TITLE
Require the latest sysctl

### LINKED ISSUE #1647: supermarket-ctl reconfigure fails on Amazon Linux 2017.03
Executing `supermarket-ctl reconfigure` fails on Amazon Linux 2017.03

```
$ sudo supermarket-ctl reconfigure
Starting Chef Client, version 13.2.20
resolving cookbooks for run list: ["omnibus-supermarket::default"]
Synchronizing Cookbooks:
  - omnibus-supermarket (1.1.0)
  - enterprise (0.11.0)
  - omnibus (5.2.1)
  - runit (3.0.5)
  - sysctl (0.9.0)
  - unicorn (2.1.2)
  - openssl (7.1.0)
  - build-essential (8.0.3)
  - chef-sugar (3.4.0)
  - chef-ingredient (2.1.3)
  - git (6.1.0)
  - homebrew (4.2.0)
  - remote_install (1.0.2)
  - seven_zip (2.0.2)
  - windows (3.1.1)
  - wix (3.2.0)
  - windows-sdk (1.0.2)
  - packagecloud (0.3.0)
  - yum-epel (2.1.2)
  - ohai (5.1.0)
  - mingw (2.0.1)
  - dmg (4.0.0)
  - compat_resource (12.19.0)
Installing Cookbook Gems:
Compiling Cookbooks...
/var/opt/supermarket/cache/cache/cookbooks/packagecloud/resources/repo.rb:10: warning: constant ::Fixnum is deprecated
Converging 78 resources
Recipe: omnibus-supermarket::config
  * linux_user[supermarket] action create (up to date)
  * group[supermarket] action create (up to date)
  * directory[/etc/supermarket] action create (up to date)
  * directory[/var/opt/supermarket] action create (up to date)
  * directory[/var/log/supermarket] action create (up to date)
  * directory[/var/opt/supermarket/etc] action create (up to date)
  * file[/etc/supermarket/supermarket.rb] action create (up to date)
  * file[/etc/supermarket/secrets.json] action create (up to date)
Recipe: omnibus-supermarket::log_management
  * directory[/var/opt/supermarket/etc/logrotate.d] action create (up to date)
  * template[/var/opt/supermarket/etc/logrotate.conf] action create (up to date)
  * template[/etc/cron.hourly/supermarket_logrotate] action create (up to date)
Recipe: omnibus-supermarket::ssl
  * directory[/var/opt/supermarket/ssl] action create (up to date)
  * directory[/var/opt/supermarket/ssl/ca] action create (up to date)
  * openssl_dhparam[/var/opt/supermarket/ssl/ca/dhparams.pem] action create (up to date)
  * openssl_x509[/var/opt/supermarket/ssl/ca/supermarket.test.nimbus.expedia.com.crt] action create (up to date)
  * link[/var/opt/supermarket/ssl/cacert.pem] action create (up to date)
Recipe: sysctl::service
  * template[/etc/rc.d/init.d/procps] action create (skipped due to only_if)
  * service[procps] action enable
    * service[procps]: Service is not known to chkconfig.
    ================================================================================
    Error executing action `enable` on resource 'service[procps]'
    ================================================================================

    Chef::Exceptions::Service
    -------------------------
    service[procps]: Service is not known to chkconfig.

    Resource Declaration:
    ---------------------
    # In /var/opt/supermarket/cache/cache/cookbooks/sysctl/recipes/service.rb

     26: service 'procps' do
     27:   supports :restart => true, :reload => true, :status => false
     28:   action :enable
     29: end

    Compiled Resource:
    ------------------
    # Declared in /var/opt/supermarket/cache/cache/cookbooks/sysctl/recipes/service.rb:26:in `from_file'

    service("procps") do
      action [:enable]
      default_guard_interpreter :default
      service_name "procps"
      enabled nil
      running nil
      masked nil
      pattern "procps"
      declared_type :service
      cookbook_name "sysctl"
      recipe_name "service"
      supports {:restart=>true, :reload=>true, :status=>false}
    end

    System Info:
    ------------
    chef_version=13.2.20
    platform=amazon
    platform_version=2017.03
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=20149;start=15:03:30;
    executable=/opt/supermarket/embedded/bin/chef-client


Running handlers:
[2017-08-05T15:03:33+00:00] ERROR: Running exception handlers
[2017-08-05T15:03:33+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-08-05T15:03:33+00:00] ERROR: Exception handlers complete
[2017-08-05T15:03:33+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2017-08-05T15:03:33+00:00] FATAL: Stacktrace dumped to /var/opt/supermarket/cache/cache/chef-stacktrace.out
[2017-08-05T15:03:33+00:00] FATAL: Stacktrace dumped to /var/opt/supermarket/cache/cache/chef-stacktrace.out
[2017-08-05T15:03:33+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-05T15:03:33+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-05T15:03:33+00:00] ERROR: service[procps] (sysctl::service line 26) had an error: Chef::Exceptions::Service: service[procps]: Service is not known to chkconfig.
[2017-08-05T15:03:33+00:00] ERROR: service[procps] (sysctl::service line 26) had an error: Chef::Exceptions::Service: service[procps]: Service is not known to chkconfig.
[2017-08-05T15:03:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2017-08-05T15:03:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

This issues seems to be caused by https://github.com/sous-chefs/sysctl/issues/85

Also, my system has chef-client 12 installed

```
$ chef-client --version
Chef: 12.21.3
```

Is there any way of overriding which version of chef-client to use in embedded supermarket as a temporary workaround?

Thanks,
N.

### PR DESCRIPTION
**Pull request by tas50**
This works on opensuse and amazon linux

Signed-off-by: Tim Smith <tsmith@chef.io>

----
Fixes #1647

### CODE REVIEW

File: omnibus/cookbooks/omnibus-supermarket/metadata.rb [hunk 1]
```diff
@@ -9,6 +9,6 @@
 depends          'enterprise'
 depends          'omnibus'
 depends          'runit', '>= 3.0.3'
-depends          'sysctl'
+depends          'sysctl', '>= 0.10.0'
```
Comment (robbkidd) [inline omnibus/cookbooks/omnibus-supermarket/metadata.rb]: Should this be `0.10.1` for [the "conf_dir not conf_file" fix](https://github.com/sous-chefs/sysctl/pull/94)?

Comment (tas50) [inline omnibus/cookbooks/omnibus-supermarket/metadata.rb]: Probably yes
