### PR TITLE
Fix signer creation in seeds

### LINKED ISSUE #1132: seeds.rb does not create test users
I'm setting up a new development environment and attempting to seed it with sample data, particularly about having a variety of users with contributor agreements. A `db/seeds.rb` comment states that [there is a way to create about 150 users](https://github.com/chef/supermarket/blob/master/db/seeds.rb#L37-L40) for a development environment.

### Current result:
```
» SEED_CLA_DATA="true" be rake db:drop db:create db:schema:load db:seed
{busy busy busy}
» be rails console
Loading development environment (Rails 4.1.12)
[1] pry(main)> User.count
   (0.6ms)  SELECT COUNT(*) FROM "users"
=> 1
```

### Expected result:
```
» SEED_CLA_DATA="true" be rake db:drop db:create db:schema:load db:seed
{busy busy busy}
» be rails console
Loading development environment (Rails 4.1.12)
[1] pry(main)> User.count
   (0.6ms)  SELECT COUNT(*) FROM "users"
=> 126
```

### Further troubleshooting

A `binding.pry` in the seeds file confirms that there are no users that exist in the DB that match [the query for individual_contributors](https://github.com/chef/supermarket/blob/master/db/seeds.rb#L43).

```
    39:   # Add 100 new individual contributors
    40:   #
    41:   existing_contributors = User.authorized_contributors.map(&:id)
    42:
    43:   individual_contributors = User.where.not(id: existing_contributors).first(100)
 => 44:   binding.pry
    45:   ActiveRecord::Base.transaction do
    46:     individual_contributors.each.with_index do |user, index|
    47:       IclaSignature.create!(
    48:         user: user,
    49:         icla: Icla.first,

[1] pry(main)> individual_contributors.count
=> 0
```

### PR DESCRIPTION
**Pull request by robbkidd**
Fixes #1132 

Adds a loop to seeds.rb creating a bunch of users for the existing "create signatures" logic to use.

In the process, discovered that the CCLA and ICLA tests were relying on spec let ordering for logic around `signed_at`. Reordered tests, instantiating the more recent signature first. This revealed that the `signed_at` passed in to the factory was being overwritten by the `before_create` callback in both signature classes. Updated the callback to use a set value or default to `Time.now` as before.

### CODE REVIEW

File: app/models/icla_signature.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ class IclaSignature < ActiveRecord::Base
 
   # Callbacks
   # --------------------
-  before_create -> (record) { record.signed_at = Time.now }
+  before_create -> (record) { record.signed_at ||= Time.now }
```
Comment (raskchanky) [inline app/models/icla_signature.rb]: I realize it was already like this, but we should be using `Time.zone.now` everywhere instead of `Time.now`.

**Comment by raskchanky** [comment]
1 minor quibble, but nothing that should prevent merging this.  :+1:

File: app/models/icla_signature.rb (hunk 1 above)
Comment (robbkidd) [inline app/models/icla_signature.rb]: Indeed. Opened #1139 to review and correct use of `Time.now`.

**Comment by robbkidd** [comment]
Thanks for the review, @raskchanky. Mergin'.
